# Generated by Django 5.0.6 on 2024-08-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_task_title_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(default='-', max_length=255),
        ),
    ]
