version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/postgres
    volumes:
      - ./app/static:/app/static
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=mysecretpassword